/*
 * ChaTex Web API
 *
 * The Web API for ChaTex
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerGen;
using WebAPI.Authentication;
using Business.Channels;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class ChannelsController : Controller
    {
        private readonly IChannelManager channelManager;

        public ChannelsController(IChannelManager channelManager)
        {
            this.channelManager = channelManager;
        }

        /// <summary>
        /// Create a channel in a group
        /// </summary>
        /// <remarks>Creates a new channel in the specified group</remarks>
        /// <param name="groupId">The id of the group to make the channel in</param>
        /// <param name="name">The name of the new channel</param>
        /// <response code="204">Channel created successfully</response>
        /// <response code="400">Name must be specified</response>
        /// <response code="401">The user was not authorized to access this resource</response>
        /// <response code="404">No group with the specified id was found</response>
        [HttpPost]
        [Route("/1.0.0/groups/{groupId}/channels")]
        [SwaggerOperation("CreateChannel")]
        [ServiceFilter(typeof(ChaTexAuthorization))]
        public virtual StatusCodeResult CreateChannel([FromRoute]int? groupId, [FromQuery]string name)
        {
            int? userId = (int?)HttpContext.Items[ChaTexAuthorization.UserIdKey];

            if (groupId == null)
            {
                return StatusCode(404);
            }

            if (name == null)
            {
                return StatusCode(400);
            }

            bool success = channelManager.CreateChannel((int)groupId, (int)userId, name);

            if (!success)
            {
                return StatusCode(401);
            }

            return StatusCode(204);
        }

        /// <summary>
        /// Delete a channel from a group
        /// </summary>
        /// <remarks>Deletes the channel from the specified group</remarks>
        /// <param name="groupId">The id of the group to delete the channel from</param>
        /// <param name="channelId">The id of the channel to delete</param>
        /// <response code="204">Channel deleted successfully</response>
        /// <response code="401">The user was not authorized to access this resource</response>
        /// <response code="404">No group or channel with the specified ids were found</response>
        [HttpDelete]
        [Route("/1.0.0/groups/{groupId}/channels/{channelId}")]
        [SwaggerOperation("DeleteChannel")]
        [ServiceFilter(typeof(ChaTexAuthorization))]
        public virtual StatusCodeResult DeleteChannel([FromRoute]int? groupId, [FromRoute]int? channelId)
        {
            int? userId = (int?)HttpContext.Items[ChaTexAuthorization.UserIdKey];

            if (groupId == null || channelId == null)
            {
                return StatusCode(404);
            }

            channelManager.DeleteChannel((int)groupId, (int)userId, (int)channelId);

            return StatusCode(204);
        }
    }
}
