/*
 * ChaTex Web API
 *
 * The Web API for ChaTex
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerGen;
using Business.Authentication;
using WebAPI.Mappers;
using Microsoft.AspNetCore.Mvc.Filters;
using Business.Groups;

namespace WebAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class GroupsController : Controller
    {
        private readonly IGroupManager groupManager;
        private readonly IUserManager userManager;
        private readonly DTOMapper dtoMapper;

        private long? userId;

        public GroupsController(IUserManager userManager, IGroupManager groupManager)
        {
            this.groupManager = groupManager;
            this.userManager = userManager;
            dtoMapper = new DTOMapper();
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            string token = HttpContext.Request.Headers["token"];
            userId = userManager.Authenticate(token);
        }

        /// <summary>
        /// Create a group
        /// </summary>
        /// <remarks>Create a group, and define group administrator</remarks>
        /// <param name="groupName">Name of the group</param>
        /// <param name="allowEmployeeSticky">Allow employee sticky</param>
        /// <param name="allowEmployeeAcknowledgeable">Allow employee acknowledgeable</param>
        /// <param name="allowEmployeeBookmark">Allow employee bookmark</param>
        /// <response code="200">The group was created, and the group administrator was successfully added</response>
        /// <response code="400">Something went wrong, and the group was not created</response>
        /// <response code="418">The user was not authorized to access this resource</response>
        [HttpPost]
        [Route("/1.0.0/groups")]
        [SwaggerOperation("CreateGroup")]
        public virtual StatusCodeResult CreateGroup([FromQuery]string groupName, [FromQuery]bool? allowEmployeeSticky, [FromQuery]bool? allowEmployeeAcknowledgeable, [FromQuery]bool? allowEmployeeBookmark)
        {
            if (userId == null)
            {
                return StatusCode(418);
            }
            groupManager.CreateGroup(userId: (int)userId, groupName: groupName,
                                     allowEmployeeSticky: (bool)allowEmployeeSticky,
                                     allowEmployeeAcknowledgeable: (bool)allowEmployeeAcknowledgeable,
                                     allowEmployeeBookmark: (bool)allowEmployeeBookmark);
            return StatusCode(200);

        }
    }
}
