/*
 * ChaTex Web API
 *
 * The Web API for ChaTex
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerGen;
using WebAPI.Models;
using Business.Messages;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Business.Models;
using WebAPI.Authentication;
using Business.Users;
using WebAPI.Models.Mappers;
using System;
using IO.Swagger.Models;
using Business.Groups;

namespace WebAPI.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserManager userManager;
        private readonly IGroupManager groupManager;

        public UsersController(IUserManager userManager, IGroupManager groupManager)
        {
            this.userManager = userManager;
            this.groupManager = groupManager;
        }

        /// <summary>
        /// Get all users
        /// </summary>
        /// <remarks>Get the available users in the system</remarks>
        /// <response code="200">Successfully retrieved all the user's</response>
        /// <response code="401">The user was not authorized to access this resource</response>
        [HttpGet]
        [Route("/1.0.0/users")]
        [SwaggerOperation("GetAllUsers")]
        [SwaggerResponse(200, type: typeof(List<UserDTO>))]
        [ServiceFilter(typeof(ChaTexAuthorization))]
        public virtual IActionResult GetAllUsers()
        {
            int callerId = (int)HttpContext.Items[ChaTexAuthorization.UserIdKey];

            IEnumerable<UserModel> users = userManager.GetAllUsers();
            IEnumerable<UserDTO> dtoResponse = users.Select(u => UserMapper.MapUserToUserDTO(u, callerId));
           
            return new ObjectResult(dtoResponse);
        }

        /// <summary>
        /// Get the available groups to a user.
        /// </summary>
        /// <remarks>Get the available groups to the user with the specified ID.</remarks>
        /// <response code="200">Successfully retrieved the user&#39;s groups</response>
        /// <response code="401">The user was not authorized to access this resource</response>
        [HttpGet]
        [Route("/1.0.0/users/me/groups")]
        [SwaggerOperation("GetGroupsForUser")]
        [SwaggerResponse(200, type: typeof(List<GroupDTO>))]
        [ServiceFilter(typeof(ChaTexAuthorization))]
        public virtual IActionResult GetGroupsForUser()
        {
            int callerId = (int)HttpContext.Items[ChaTexAuthorization.UserIdKey];

            IEnumerable<GroupModel> groups = groupManager.GetGroupsForUser(callerId);
            List<GroupDTO> dtoResponse = groups.Select(g => GroupMapper.MapGroupToGroupDTO(g)).ToList();

            return new ObjectResult(dtoResponse);
        }

        /// <summary>
        /// Login a user
        /// </summary>
        /// <remarks>Login the user with the specified e-mail</remarks>
        /// <param name="userEmail">The user&#39;s email</param>
        /// <response code="200">The user was successfully logged in</response>
        /// <response code="401">No user with the specified e-mail was found</response>
        [HttpGet]
        [Route("/1.0.0/users/login")]
        [SwaggerOperation("Login")]
        [SwaggerResponse(200, type: typeof(string))]
        public virtual IActionResult Login([FromQuery]string userEmail)
        {
            if (string.IsNullOrWhiteSpace(userEmail))
            {
                return BadRequest("An email must be specified!");
            }

            string token = userManager.Login(userEmail);

            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound("No user with the specified email was found!");
            }
            
            return Content(token);
        }

        /// <summary>
        /// Update a user
        /// </summary>
        /// <remarks>Update an existing user in the database</remarks>
        /// <param name="userId">User id of user to update</param>
        /// <param name="updateUserDTO">The name of the user</param>
        /// <response code="200">The user was successfully updated</response>
        /// <response code="404">No user with the specified id was found</response>
        [HttpPut]
        [Route("/1.0.0/users/{userId}")]
        [SwaggerOperation("UpdateUser")]
        [ServiceFilter(typeof(ChaTexAuthorization))]
        public virtual IActionResult UpdateUser([FromRoute]int? userId, [FromBody]UpdateUserDTO updateUserDTO)
        {
            int callerId = (int)HttpContext.Items[ChaTexAuthorization.UserIdKey];
            
            if(userId == null || updateUserDTO == null)
            {
                return StatusCode(400);
            }

            userManager.UpdateUser(callerId, new UserModel()
            {
                Id = userId,
                FirstName = updateUserDTO.FirstName,
                MiddleInitial = updateUserDTO.MiddleInitial?[0],
                LastName = updateUserDTO.LastName,
                Email = updateUserDTO.Email,
                IsDeleted = updateUserDTO.IsDeleted
            });

            return StatusCode(204);
        }
    }
}
