/*
 * ChaTex Web API
 *
 * The Web API for ChaTex
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddUsersToChatDTO :  IEquatable<AddUsersToChatDTO>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddUsersToChatDTO" /> class.
        /// </summary>
        /// <param name="ChatId">ChatId (required).</param>
        /// <param name="UserIds">UserIds (required).</param>
        public AddUsersToChatDTO(int? ChatId = null, List<int?> UserIds = null)
        {
            // to ensure "ChatId" is required (not null)
            if (ChatId == null)
            {
                throw new InvalidDataException("ChatId is a required property for AddUsersToChatDTO and cannot be null");
            }
            else
            {
                this.ChatId = ChatId;
            }
            // to ensure "UserIds" is required (not null)
            if (UserIds == null)
            {
                throw new InvalidDataException("UserIds is a required property for AddUsersToChatDTO and cannot be null");
            }
            else
            {
                this.UserIds = UserIds;
            }
            
        }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [DataMember(Name="chatId")]
        public int? ChatId { get; set; }

        /// <summary>
        /// Gets or Sets UserIds
        /// </summary>
        [DataMember(Name="userIds")]
        public List<int?> UserIds { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddUsersToChatDTO {\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  UserIds: ").Append(UserIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((AddUsersToChatDTO)obj);
        }

        /// <summary>
        /// Returns true if AddUsersToChatDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of AddUsersToChatDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddUsersToChatDTO other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.ChatId == other.ChatId ||
                    this.ChatId != null &&
                    this.ChatId.Equals(other.ChatId)
                ) && 
                (
                    this.UserIds == other.UserIds ||
                    this.UserIds != null &&
                    this.UserIds.SequenceEqual(other.UserIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ChatId != null)
                    hash = hash * 59 + this.ChatId.GetHashCode();
                if (this.UserIds != null)
                    hash = hash * 59 + this.UserIds.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(AddUsersToChatDTO left, AddUsersToChatDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddUsersToChatDTO left, AddUsersToChatDTO right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
